services:
  neo4j-service:
    build:
      context: .
      dockerfile: neo4j.Dockerfile
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - server-side-net
    environment:
      NEO4J_AUTH: "neo4j/12345678"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: "[\"apoc\"]"
    volumes:
      - db-data:/data
    command: neo4j start

  fastapi:
    build: .
    depends_on:
      - neo4j-service
    container_name: fastapi-application
    ports:
      - '8000:8000'
    networks:
      - server-side-net
    environment:
      NEO4J_URI: "neo4j://neo4j-service:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "12345678"
      DB_NAME: "subway"

    command: sh -c "/app/infra/run.sh"

networks:
  server-side-net:

volumes:
  db-data:
