services:
  neo4j-service:
    image: docker.arvancloud.ir/neo4j
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - server-side-net
    environment:
      NEO4J_AUTH: "neo4j/12345678"
    volumes:
      - db-data:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  fastapi:
    build: .
    depends_on:
      neo4j-service:
        condition: service_healthy
    container_name: fastapi-application
    ports:
      - '8000:8000'
    networks:
      - server-side-net
    environment:
      NEO4J_URI: "neo4j://neo4j-service:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "12345678"
      DB_NAME: "subway"

    command: fastapi run

networks:
  server-side-net:

volumes:
  db-data:
